#require zsh-syntax-highlighting, zsh-autosuggestions and agnoster theme in /usr/share/zsh/functions/Prompts/prompt_agnoster_setup
autoload -Uz compinit promptinit
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search

compinit
fpath=("$HOME/.local/share/zsh/theme" "$fpath[@]")
promptinit
prompt myprompt

# color for ls
eval $(dircolors $HOME/.local/share/dircolors/dircolors.ansi-dark)

# suggestions navigable, colored with LS_COLORS and case-insensitive
zstyle ':completion:*' menu select 
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 

export EDITOR="nvim"
export VISUAL="nvim"
export PATH="$PATH:$HOME/.local/bin"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# history setting
export HISTFILE=$XDG_CACHE_HOME/zsh/zsh_history
export HISTSIZE=5000
export SAVEHIST=5000
setopt appendhistory
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space

#use vim key, normally enable by default with EDITOR=nvim but better safe than sorry
bindkey -v
KEYTIMEOUT=1 #timeout of 10ms, use when pressing esc to switch to normal mode

#bind arrow up and down as well as j and k in nmod to history search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -- "^[OA" up-line-or-beginning-search
bindkey -- "^[OB" down-line-or-beginning-search
bindkey -- "^[[A" up-line-or-beginning-search
bindkey -- "^[[B" down-line-or-beginning-search
bindkey -M vicmd 'k' up-line-or-beginning-search
bindkey -M vicmd 'j' down-line-or-beginning-search

cat /etc/*-release | grep archlinux &> /dev/null
if [ $? -eq 0 ];then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else 
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi



alias "vim"="nvim"

# ls alias
alias "ls"="ls --color=tty"
alias "ll"="ls -lh"
alias "la"="ls -lAh"

# git alias
alias "gc"="git commit -v"
alias "gca"="git commit -av"
alias "gst"="git status"

#auto rescale image in feh
alias -g 'feh'='feh --scale-down'

#cd alias
alias ".."="cd .."
alias "..."="cd ../.."
alias "...."="cd ../../.."

#relocate all the .folder where they should be (aka not polluting my $HOME)
export LESSHISTFILE=$XDG_CACHE_HOME/less/lesshst
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export PYLINTHOME=$XDG_CACHE_HOME/pylint
export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/pythonrc #allows to relocate the history
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

